link g2pservice python package in /opt

diff --git a/roles/g2pservice/tasks/main.yml b/roles/g2pservice/tasks/main.yml
--- a/roles/g2pservice/tasks/main.yml
+++ b/roles/g2pservice/tasks/main.yml
@@ -40,3 +40,20 @@
       when: '"all" in services or item in services'
       with_items:
         - g2pservice
+
+    - name: Link Python package installation in opt/
+      become: "{{lm_become}}"
+      become_user: root
+      shell: |
+        export DIR=$(python3 -c "import {{item}}; print({{item}}.__path__[0])")
+        if [ ! -e "$DIR" ]; then
+            echo "Unable to find dir"
+            exit 2
+        fi
+        if [ -e "{{lm_prefix}}/opt/{{item}}" ]; then
+          rm "{{lm_prefix}}/opt/{{item}}"
+        fi
+        ln -sf $DIR {{lm_prefix}}/opt/{{item}}
+      with_items:
+        - g2pservice
+      environment: "{{lm_env}}"
