fixed recompilation check and simplified bootstrap

diff --git a/roles/ac_github/tasks/main.yml b/roles/ac_github/tasks/main.yml
--- a/roles/ac_github/tasks/main.yml
+++ b/roles/ac_github/tasks/main.yml
@@ -45,17 +45,22 @@
 
 - name: "{{repo}} - Checking whether recompilation is needed"
   shell: |
-      {% if ac_github_updated is defined and ac_github_updated.stdout == 1 %}
+      {% if ac_github_updated is defined and ac_github_updated.stdout|int == 1 %}
       #an earlier compilation was (re)performed so we update everything thereafter as well
       echo 1 && exit 0
+      echo "Compilation required because of earlier updates...">&2
       {% endif %}
       available=$(git rev-parse HEAD)
+      echo "Available commit: $available">&2
       if [ -f .installed-commit.lamachine ]; then
         installed=$(cat .installed-commit.lamachine)
-        if [[ "$available" == "$installed" ]]; then
-          echo 0
+        echo "Installed commit: $installed">&2
+        if [ "$available" = "$installed" ]; then
+          echo "No recompilation necessary...">&2
+          echo 0 && exit 0
         fi
       fi
+      echo "Scheduling compilation...">&2
       echo 1
   args:
     chdir: "{{ source_path }}/{{repo}}"
@@ -67,12 +72,12 @@
   vars:
     pkg_source_dir: "{{ source_path }}/{{ repo }}"
     pkg_name: "{{ repo }}"
-  when: ac_github_updated.stdout == 1
+  when: ac_github_updated.stdout|int == 1
 
 - name: "{{repo }} - Registering current version"
   shell: "git rev-parse HEAD > .installed-commit.lamachine"
   args:
     chdir: "{{ source_path }}/{{ repo }}"
-  when: ac_github_updated.stdout == 1 and make_install_result is defined and make_install_result.rc == 0
+  when: ac_github_updated.stdout|int == 1 and make_install_result is defined and make_install_result.rc == 0
 
 
