refactoring error handling (migrating into lower level)

diff --git a/roles/lamachine_run/tasks/main.yml b/roles/lamachine_run/tasks/main.yml
--- a/roles/lamachine_run/tasks/main.yml
+++ b/roles/lamachine_run/tasks/main.yml
@@ -1,28 +1,36 @@
 ---
-    - name: "Running {{command}}"
-      shell: |
-          if [ {{prefer_global|int}} -ne 1 ]; then
-              if [ -e {{homedir}}/bin/lamachine-{{ conf_name }}.activate ]; then
-                  source {{homedir}}/bin/lamachine-{{ conf_name }}.activate
-              else
-                  echo "Activation script {{homedir}}/bin/lamachine-{{ conf_name }}.activate not found! ">&2
-                  exit 2
+    - block:
+        - name: "Running {{command}}"
+          shell: |
+              if [ {{prefer_global|int}} -ne 1 ]; then
+                  if [ -e {{homedir}}/bin/lamachine-{{ conf_name }}.activate ]; then
+                      source {{homedir}}/bin/lamachine-{{ conf_name }}.activate
+                  else
+                      echo "Activation script {{homedir}}/bin/lamachine-{{ conf_name }}.activate not found! ">&2
+                      exit 2
+                  fi
               fi
-          fi
-          hash -r  #clear cache
-          echo "Running: {{command}}">&2
-          echo "Run environment:">&2
-          echo "    LM_NAME=$LM_NAME">&2
-          echo "    PATH=$PATH">&2
-          echo "    LD_LIBRARY_PATH=$LD_LIBRARY_PATH">&2
-          echo "    VIRTUAL_ENV=$VIRTUAL_ENV">&2
-          echo "    PYTHONPATH=$PYTHONPATH">&2
-          {{command}}
-      args:
-          executable: /bin/bash
-          chdir: "{% if chdir is defined %}{{ chdir }}{% else %}{{homedir}}{% endif %}"
-      register: lamachine_run
-      changed_when: 'sideeffects is defined and sideeffects == True'
+              hash -r  #clear cache
+              echo "Run environment:">&2
+              echo "    LM_NAME=$LM_NAME">&2
+              echo "    PATH=$PATH">&2
+              echo "    LD_LIBRARY_PATH=$LD_LIBRARY_PATH">&2
+              echo "    VIRTUAL_ENV=$VIRTUAL_ENV">&2
+              echo "    PYTHONPATH=$PYTHONPATH">&2
+              echo "    PYTHON=$(which python)">&2
+              echo "    PIP=$(which pip)">&2
+              echo "    CONDA=$(which conda)">&2
+              echo "Running: {{command}}">&2
+              {{command}}
+          args:
+              executable: /bin/bash
+              chdir: "{% if chdir is defined %}{{ chdir }}{% else %}{{homedir}}{% endif %}"
+          register: lamachine_run
+          changed_when: 'sideeffects is defined and sideeffects == True'
+      rescue:
+        - name: "Package list at time of failure when running {{command}}"
+          shell: "{{local_prefix}}/bin/conda list -p {{local_prefix}}"
+          when: localenv_type == "conda" and not prefer_global
 
 
 
