can not use include_role in handlers

diff --git a/roles/lamachine-register/handlers/main.yml b/roles/lamachine-register/handlers/main.yml
--- a/roles/lamachine-register/handlers/main.yml
+++ b/roles/lamachine-register/handlers/main.yml
@@ -1,7 +1,20 @@
 ---
   - name: lamachine-build-registry
-    include_role:
-      name: lamachine-run
-    vars:
-      command: lamachine-build-registry
-      chdir: "{{ lm_prefix }}/var"
+    shell: |
+        #!/bin/bash
+        export LM_QUIET=1
+        if [ -e {{homedir}}/bin/lamachine-{{ conf_name }}-activate ]; then
+            source {{homedir}}/bin/lamachine-{{ conf_name }}-activate
+        else
+            echo "Activation script {{homedir}}/bin/lamachine-{{ conf_name }}-activate not found! ">&2
+            exit 2
+        fi
+        lamachine-build-registry
+    args:
+        executable: /bin/bash
+        chdir: "{% if chdir is defined %}{{ chdir }}{% else %}{{homedir}}{% endif %}"
+    environment:
+        PATH: "{{ansible_env.HOME}}/bin:{{ansible_env.PATH}}"
+    ignore_errors: "{{allow_failure|default(False)}}"
+    register: lamachine_run
+    changed_when: 'sideeffects is defined and sideeffects == True'
